---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yml: AgCNpfYGyKAa+vBVYG0698AIlya4ezXRB7YRtXDyTeoXw/R8URizzmNAp96U5PV2zdMTZYjLj9dmFck8uAbtPudKlq3eQbs0NBwg7awIDWw5HwbN7yfLUXisNJ8IBcNrlYO3EZji29hNfE0WBWL8xuu7gDaDLIEtyBzjTbn9j0czkxCiBDEtBB+c0JVeGakQjMMV1Dg9VYLzo4/Rm51FXNxe4O9Qtx4u4bcGDAHD4S0PckFxoqw15OHTTaXoy419vBcdAvM+2w8vbcDyaxJx1tEToWdWXky+O0ZdwD1g6Hstb1apDVopJwyR+D4NWW7aiscpCVRECWfqz/TSEnEGythfIVNmNogqUHpOnhKO+l5fEaH0c9IYWAdUYIL1uwlVUaaXSI4MgSyTXOXmjatmIdomegVxuANzHtExwxxS1cCedQwxK27FnweyB/D0KfWmSzNQoVJelTspdsjVK4QRxvo5wEz6Wkhz1jtoJDa2gUiXJ4c/UG0P45xGHD2VTp7P49M206h3zcvtCfmxbRVG4/PVtHtYQulXnjyROaGh/2l6B5KPZ+G/hFTgMPMHAdXVSDF71YAwEHf9ByOrWL45r7/5tlVS5uLiJbE/NSZ83prXu3hfdKw7a+8KH3XhzU+0m6M/Usx/rwAxMB9zzOoQz7hMhXsIjBA9VB5b58g6uNJvFnboOkB4NhJ2M0PAEQBpUDeq4TP9wpdiELK4EUxT/IuJY/blFwVpO9NYrZ+hSwTZZpKovwX0WSHz3Ep6Fi4namusnRKHRQ9XbQzyECe14trpWJ8sktUDJXMPM+7jVV6nrZi800TeFsv5WtF0b1/2o0tnQPG+LqzvZhr+6gps/xQShA4ROO91aMM/dNW1b0GT6gym+nueukL4SLDP8w30BXcSygZFvDlOgrd1I0usaJnDNj7zWB6QNEjTd+KOPG+wDcxxFfOGkyQEb99mDl4qzuytZT3vmRHDVwMPkYoIbPKeI+Nm8pD/fsNV1nl0gmzbof4PuvaA8V6G0HNb0+43P9KlwnwyLIJrZPSoBBBPLGraNCZv7/HDCA==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
